services:
    core_access_management_bundle.model:
            class:        BiberLtd\Bundle\AccessManagementBundle\Services\AccessManagementModel
            arguments:    [@kernel, "default", "doctrine"]